GET http://localhost:8080/books


###
GET http://localhost:8080/books/2


###
POST http://localhost:8080/books
Content-Type: application/json

{
  "id": 4,
  "title": "Book By Spring Data 3",
  "isbn": "3000",
  "price": 3000.00
}


###
PUT http://localhost:8080/books
Content-Type: application/json

{
  "id": 1,
  "title": "Book Title 1",
  "isbn": "2006",
  "price": 299.00
}
###
DELETE http://localhost:8080/books/5
